version: '3'

services:
  db:
    image: postgres
    environment:
     POSTGRES_PASSWORD: zxcvbnm,./
     PGDATA: /var/lib/postgresql/data/pgdata
     POSTGRES_DB: course_work_8
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis


  habit_service:
    build: .
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CELERY_BEAT_SCHEDULER: "django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      db:
        condition: service_healthy

#  celery:
#    container_name: celery_worker
#    build: .
#    command: keepfresh auto-restart -c echo "Hellow"
#    environment:
#      CELERY_BROKER_URL: "redis://redis:6379/0"
#      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
#      CELERY_BEAT_SCHEDULER: "django_celery_beat.schedulers:DatabaseScheduler"
#    depends_on:
#      - redis
#      - habit_service

  celery_beat:
    container_name: celery_beat
    tty: true
    build: .
    command: celery -A config beat -l INFO
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CELERY_BEAT_SCHEDULER: "django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - db
      - habit_service